# Generated by Django 4.0 on 2021-12-19 10:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(default='')),
                ('timing', models.CharField(max_length=250)),
                ('attendees', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
