# Generated by Django 4.0 on 2021-12-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='organizers',
            field=models.CharField(default='', max_length=550),
        ),
    ]
